# Generated by Django 4.2.3 on 2023-07-11 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_date', models.DateField()),
                ('diet_time', models.TimeField()),
                ('diet_description', models.TextField()),
                ('approximate_calorie', models.IntegerField(default=0)),
                ('record_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('fitness_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
