# Generated by Django 4.2.3 on 2023-07-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Regular'), (2, 'Premium'), (3, 'Manager')], default=1),
        ),
    ]
